### ISSUE TITLE
Add markdown file 

### ISSUE THREAD

**Issue by ZacharyHimmelberger** [ZacharyHimmelberger/data-processing-in-R#7]
This repo will be used to demonstrate how we fix common issues. We should put together a markdown file that provides a skeleton for what this final product will look like. We can then work in that markdown file as a team. 

The initial commit should include the libraries we will be using and some basic descriptions. 

I'm not sure whether it is best to use Quarto, Markdown, or a Notebook. I'm also not sure if we should use one file per solution or if we should include everything in one document. Thoughts?

**Comment by mtbest** [comment]
See Matt's pull request on #10 .
