### ISSUE TITLE
What's a good timeline for us to resolve these issues?

### ISSUE THREAD

**Issue by mtbest** [ZacharyHimmelberger/data-processing-in-R#8]
Zach - what do you think is a good timeline for us to resolve the issues you assigned to us? Also, is this the right way to communicate on GitHub? Or is there a better way?

**Comment by ZacharyHimmelberger** [comment]
Great question. I wouldn't open up a new issue to ask this question. I would instead ask the question within an issue. Generally speaking, if no code changes, then it isn't an issue. The reason for this is that the issues provide a nice way of tracking what we've done, whereas this question isn't necessarily something we need to track. 

But... to answer your question: I think I could tackle one issue by the end of this week. What works for you?
